# Autogenerated by LiteX
set -e
source /home/travis/build/rohitk-singh/litex-buildenv/build/Xilinx/opt/Xilinx/14.7/ISE_DS/settings64.sh

xst -ifn top.xst

ngdbuild  -uc top.ucf top.ngc top.ngd
map -ol high -w -o top_map.ncd top.ngd top.pcf
par -ol high -w top_map.ncd top.ncd top.pcf
bitgen -g Binary:Yes -w top.ncd top.bit
